### ISSUE TITLE
Feature: Support Multiple Realms with Docker Installation

### ISSUE THREAD

**Issue by ReynoldsCahoon** [azerothcore/azerothcore-wotlk#5230]
**Describe your feature request or suggestion in detail**

Users should have the ability to add realms to their docker installation.

**Describe a possible solution to your Feature or Suggestion in detail**

I think (and I'm scratching my head because there's a lot to the build process of the docker containers) that basically you'd need to:

1. Update `azerothcore-wotlk/docker/database/generate-databases.sh` to create more (dependent on the number of additional realms you want) `acore_world` and `acore_character` databases (with names appended by a realm number, i.e. `acore_world_realm1`).
2. Add additional services to the `azerothcore-wotlk/docker-compose.yml` for each new realm. Something like:
```yml
# Generate new service names for new realms
ac-worldserver_realm1:
    stdin_open: true
    tty: true
    # Would the image need to change?
    image: azerothcore/worldserver
    restart: unless-stopped
    privileged: true
    build:
      context: ./docker/worldserver
      dockerfile: Dockerfile
    networks:
      - ac-network
    ports:
      # Set external ports to incremented value, avoid duplicates, might have
      # this wrong, not very familiar with what the left/right values denote.
      - ${WORLD_EXTERNAL_PORT:-8086}:8086
      - ${SOAP_EXTERNAL_PORT:-7879}:7879
    volumes:
      # This part is more hazy to me. data should certainly be shared (unless
      # one realm has different content than another), but I believe that
      # only the worldserver.conf and perhaps the log directories have to be
      # different.
      - type: bind
        source: ./docker/realmserver1/bin
        target: /azeroth-server/bin
      - type: bind
        source: ${WORLDSERVER_ETC:-./docker/worldserver/etc}
        target: /azeroth-server/etc
      - type: bind
        source: ${WORLDSERVER_LOGS:-./docker/realmserver1/logs}
        target: /azeroth-server/logs
      - type: bind
        source: ${WORLDSERVER_DATA:-./docker/worldserver/data}
        target: /azeroth-server/data
    depends_on:
      - ac-database
```
3. The `worldserver.conf` found in the `./docker/realmserver1/bin` from the step above would need to include these values:
```bash
WorldServerPort       = 8086
SOAP.IP               = "ac-worldserver-realm1"
SOAP.Port             = 7879
LoginDatabaseInfo     = "ac-database;3306;root;password;acore_auth"
WorldDatabaseInfo     = "ac-database;3306;root;password;acore_world_realm1"
CharacterDatabaseInfo = "ac-database;3306;root;password;acore_characters_realm1"
```
4. Duplicate the entry in your `acore_auth.realmlist` table for the initial `Azerothcore` realm, changing the `name` to whatever you want to call it and the  `port` value to match the realm's port value (as configured above)

**Additional context**

I think that's the gist of it. You'd run the `docker-compose up` command and the services would run as before all at once in their individual containers.

I'm certain someone with more knowledge of how these containers are built and configured could actually add a script to generate this data automatically post-install. Something like an `addrealm.sh` or something.
