### ISSUE TITLE
Feature:[Suggestion] Docker Container TimeZone should be same with Host

### ISSUE THREAD

**Issue by betayi** [azerothcore/azerothcore-wotlk#6532]
**Describe your feature request or suggestion in detail**

The Dockerfile make TZ defined as "ETC/UTC",
but in other tz country , it‘s a confusion with reality time,
So, why not make the tz same with the host  as default value ? or arg definable in config?

**Describe a possible solution to your Feature or Suggestion in detail**

**Additional context**

014816065922+

**Comment by Rastrian** [comment]
Its possible set a environment variable on docker container, by default has an file for this, in the path `conf/dist/env.ac`

There you can just put something like: ```TZ=Europe/Istanbul``` or your desired timezone.

I think just add a comment in this file for explain how to change the timezone can be a plausible solution. About sync default value with the host, i don't found a good solution yet.

**Comment by Sedatyf** [comment]
Does this have been fixed? Why closing it so suddenly?

**Comment by Routhinator** [comment]
For anyone finding this when looking for any instructions on how to get server time correct - there is an undocumented Build Arg for the containers for timezone. You can modify this using a docker-compose.override.yml:

```yaml
services:
  ac-worldserver:
    build:
      context: .
      target: worldserver
      dockerfile: apps/docker/Dockerfile
      args:
        TZ: America/Vancouver
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
    environment:
      AC_ALLOW_TWO_SIDE_INTERACTION_CALENDAR: "1" # AllowTwoSide.Interaction.Calendar
  ac-db-import:
    build:
      context: .
      target: db-import
      dockerfile: apps/docker/Dockerfile
      args:
        TZ: America/Vancouver
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
    environment:
      AC_UPDATES_EXCEPTION_SHUTDOWN_DELAY: 5m
  ac-authserver:
    build:
      context: .
      target: authserver
      dockerfile: apps/docker/Dockerfile
      args:
        TZ: America/Vancouver
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
  ac-client-data-init:
    build:
      context: .
      target: client-data
      dockerfile: apps/docker/Dockerfile
      args:
        TZ: America/Vancouver
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
  ac-tools:
    build:
      context: .
      target: tools
      dockerfile: apps/docker/Dockerfile
      args:
        TZ: America/Vancouver
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}
  ac-dev-server:
    build:
      context: .
      target: dev
      dockerfile: apps/docker/Dockerfile
      args:
        TZ: America/Vancouver
        USER_ID: ${DOCKER_USER_ID:-1000}
        GROUP_ID: ${DOCKER_GROUP_ID:-1000}
        DOCKER_USER: ${DOCKER_USER:-acore}

```

Unfortunately I needed to add the context, dockerfile and target options because unlike other parts of the docker-compose, the `build` key doesn't seem to get deep-merged and thus overriding one arg means needing to add _all_ of that to the override file.
